# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeojsonFiller
                                 A QGIS plugin
 Allows to fill imported geojson layers with pre-defined field values
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-22
        copyright            : (C) 2023 by Sebastian Bullinger
        email                : sebastianbullinger@yahoo.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeojsonFiller class from file GeojsonFiller.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geojson_filling import GeojsonFiller
    return GeojsonFiller(iface)
